### ISSUE TITLE
Issues on Android (Firefox & Chrome)

### ISSUE THREAD

**Issue by apulley** [davatron5000/TimeJump#13]
Anyone else have issues with mobile browsers? The player never seems to jump to the specific time ... maybe a problem with the event listeners?

**Comment by davatron5000** [comment]
Possibly. It doesn't work on iOS either. I know they've disabled it entirely. A few possible explanations
- Perhaps auto-seeking audio is simply disabled in most mobile browsers at this point. 
- I'm surprised that Firefox doesn't do it either. Possibly a hardware level thing.
- It could also be because the audio hasn't loaded and the `canplay` event is still waiting to fire.
- Maybe the server you're using doesn't support content "[chunking](http://en.wikipedia.org/wiki/Chunked_transfer_encoding)"

I'll investigate it further when I have more time.

**Comment by apulley** [comment]
I've been testing on Android Chrome. It's definitely the ol' autoplay issue. For jumplinks to work, the player has to be currently playing.

**Comment by davatron5000** [comment]
Does your fix in #14 solve it? I can merge that in if you can confirm a fix there.

**Comment by apulley** [comment]
Sorry, I should have provided more context for the pull request #14 ... it has nothing to do with this. I'll add additional comments in the pull req.

For jumplinks to work in mobile, somehow working in a click method, instead of hash change, into initiating the play method might do the trick. :\

This looks really promising as far as autoplay in mobile goes .. maybe something to consider.
http://blog.foolip.org/2014/02/10/media-playback-restrictions-in-blink/
Demo
http://foolip.org/2014/02/10/media-playback-restrictions-in-blink/demo.html
